# Generated by Django 3.2.7 on 2021-09-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('solved', 'Solved'), ('unsolved', 'Unsolved'), ('frozen', 'Frozen')],
                                   default='unsolved', max_length=8),
        ),
    ]
