# Generated by Django 3.2.7 on 2021-09-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_rename_text_ticket_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='message',
            new_name='task',
        ),
    ]
